package S06;
// Section 6, Video 31
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class S06_06 {
    public static void main(String[] args) throws InterruptedException {

        WebDriver driver = new ChromeDriver();
        String facebookURL = "http://facebook.com";
        String googleURL = "http://google.com";
        String saleforceLoginURL = "https://login.salesforce.com/";
        String rediffLoginURL = "https://mail.rediff.com/";
        driver.manage().window().maximize();
        driver.get(facebookURL);

        // CSS
        // Both Xpath and CSS can be generated by the help of the browser tools, like Chrome and FireFox.
        // The tools are not always accurate so care must be taken and they should be validated.
        // Right click on the HTML properties that is desired and under copy there will be different choices to copy.
        // CSS from different browser may not always be the same, that is ok. CSS' may be different.
        driver.findElement(By.cssSelector("#email")).sendKeys("Hello");
        driver.findElement(By.cssSelector("#pass")).sendKeys("123456");
        driver.findElement(By.cssSelector("#u_0_b")).click();

        Thread.sleep(2000);
        driver.quit();
    }
}
